default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end



  platform :ios do
  desc "Runs all the tests"
  lane :test do
    run_tests(scheme: "Third.xcscheme")
  end


  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end
